### PR TITLE
Forward compatible updates for TS 2.4

### PR DESCRIPTION
**Pull request by kitsonk**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [X] Unit or Functional tests are included in the PR

**Description:**

This PR is a forward compatible change to address issues when migrating to TS2.4.

### CODE REVIEW

**Comment by kitsonk** [comment]
Refs dojo/meta#189

**Comment by agubler** [comment]
Looks good, but there are test failures.

**Comment by kitsonk** [comment]
Yeah, [master](https://travis-ci.org/dojo/loader/builds/234737977) is failing with the same errors.  Appears to be some sort of regression with Firefox when running in a CSP mode.  I will open a separate issue.

**Comment by kitsonk** [comment]
Refs #138

**Pull request merged**
